# Generated by Django 2.2.5 on 2019-10-15 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191015_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='fav_jobs',
            new_name='fav_home',
        ),
    ]
