# Generated by Django 2.2.5 on 2019-10-23 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20191022_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fav_books',
            field=models.ManyToManyField(related_name='saved_books', to='myapp.User'),
        ),
        migrations.AddField(
            model_name='book',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='myapp.User'),
        ),
    ]
